name: Build and Release

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Build binary
        run: |
          mkdir -p dist

          if [ "${{ matrix.goos }}" = "windows" ]; then
            EXT=".exe"
          else
            EXT=""
          fi

          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} \
          go build -o dist/netcheckup-${{ matrix.goos }}-${{ matrix.goarch }}$EXT ./cmd/netcheckup

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: netcheckup-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/*
